### PR TITLE
added dan object + qr code

### PR DESCRIPTION
**Pull request by dengel29**

### CODE REVIEW

**Comment by dengel29** [comment]
Hi did I do it wrong?

**Comment by tgenaitay** [comment]
@dengel29 well I think it was closed by accident or by confusion with "Dan Li" who submitted right before. Sorry about this.

One thing to fix: you're currently breaking our data array - we need a comma after the latest object. Can you add one ore commit on this PR?

**Comment by dengel29** [comment]
Ah okay, I'll fix it and resubmit

**Comment by dengel29** [comment]
Hi, committed again, fixed that error in the data structure.

**Pull request merged**
